FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# API Description

Gives description of the API

## Description [/Description]

### Get API Description [GET]

+ Response 200 (application/json)

        [
            {
                "message": "Hello World!!!"
                
            }
        ]